apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: openmrsdb
    environment: dev
  name: openmrsdb
spec:
  selector:
    matchLabels:
      app: openmrsdb
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: openmrsdb
        environment: dev
    spec:
      containers:
        - env:
            - name: MYSQL_DATABASE
              value: openmrs
            - name: MYSQL_PASSWORD
              value: password
            - name: MYSQL_ROOT_PASSWORD
              value: adminAdmin!123
            - name: MYSQL_USER
              value: openmrs-user
          image: bahmni/openmrs-db:demo-latest
          name: openmrsdb
          ports:
            - containerPort: 3306
          resources: {}
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: openmrsdbdata
      restartPolicy: Always
      volumes:
        - name: openmrsdbdata
          persistentVolumeClaim:
            claimName: openmrsdbdata-pvc
