apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: openelisdb
    environment: dev
  name: openelisdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: openelisdb
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: openelisdb
        environment: dev
    spec:
      containers:
        - env:
            - name: POSTGRES_DB
              value: postgres
            - name: POSTGRES_PASSWORD
              value: postgres
            - name: POSTGRES_USER
              value: postgres
          image: bahmni/openelis-db:demo-latest
          name: openelisdb
          ports:
            - containerPort: 5432
          resources: {}
          volumeMounts:
            - mountPath: /resources/db-dump
              name: openelis-db-dump
            - mountPath: /var/lib/postgresql/data
              name: openelisdbdata
      restartPolicy: Always
      volumes:
        - name: openelis-db-dump
          persistentVolumeClaim:
            claimName: openelis-db-dump-pvc
        - name: openelisdbdata
          persistentVolumeClaim:
            claimName: openelisdbdata-pvc
