name: Continuous Integration-v0.94
on:
  push:
    branches:
      - master
env:
  ORG_NAME: mohan-13
  EVENT_TYPE: bahmni-package-0.94-trigger
jobs:
  demo:
    name: Trigger Workflows
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dependent-repos: ["openerp-atomfeed-service","odoo-modules"]
    steps:
      - name: Create repository_dispatch
        env:
          REPOSITORY_NAME: ${{ matrix.dependent-repos }}
        run : |
              trigger_result=$(curl -s -o trigger_response.txt -w "%{http_code}" -X POST -H "Accept: application/vnd.github.v3+json" -H 'authorization: Bearer ${{ secrets.WORKFLOW_TRIGGER_TOKEN }}' https://api.github.com/repos/${ORG_NAME}/${REPOSITORY_NAME}/dispatches -d '{"event_type":"${EVENT_TYPE}"}')
              if [ $trigger_result == 204 ];then
                echo "Trigger to $ORG_NAME/$REPOSITORY_NAME Success"
              else
                echo "Trigger to $ORG_NAME/$REPOSITORY_NAME Failed"
                cat trigger_response.txt
                exit 1
              fi
